In [8]:
from fin_data import DailyTimeSeries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline

In [3]:
import sys

In [192]:
import scipy as sp

In [5]:
sys.path.insert(0, '/home/joe2/Documents/LambdaSchool/labs_ir/repos/Data-Science/data')

In [4]:
print(sys.path)

['', '/home/joe2/anaconda3/envs/riskylobster/lib/python36.zip', '/home/joe2/anaconda3/envs/riskylobster/lib/python3.6', '/home/joe2/anaconda3/envs/riskylobster/lib/python3.6/lib-dynload', '/home/joe2/anaconda3/envs/riskylobster/lib/python3.6/site-packages', '/home/joe2/anaconda3/envs/riskylobster/lib/python3.6/site-packages/IPython/extensions', '/home/joe2/.ipython']


In [9]:
apple = DailyTimeSeries('AAPL')
dfaapl = apple.initiate()

################################################################### 
 Ticker:  AAPL 
 Last Refreshed:  2019-08-28 
 Data Retrieved:  Daily Prices (open, high, low, close) and Volumes 
 ###################################################################


In [24]:
apple.list_available_fundamentals()

['operatingrevenue',
 'totalrevenue',
 'operatingcostofrevenue',
 'totalcostofrevenue',
 'totalgrossprofit',
 'sgaexpense',
 'rdexpense',
 'totaloperatingexpenses',
 'totaloperatingincome',
 'otherincome',
 'totalotherincome',
 'totalpretaxincome',
 'incometaxexpense',
 'netincomecontinuing',
 'netincome',
 'netincometocommon',
 'weightedavebasicsharesos',
 'basiceps',
 'weightedavedilutedsharesos',
 'dilutedeps',
 'weightedavebasicdilutedsharesos',
 'basicdilutedeps',
 'cashdividendspershare',
 'date',
 'fiscal_year',
 'quarter']

In [10]:
funs = ['totalrevenue',  'totalcostofrevenue', 'totalgrossprofit', 'totalpretaxincome', 'weightedavebasicdilutedsharesos', 'cashdividendspershare', 'quarter']
techs = ['SMA', 'WMA', 'STOCH', 'ROC', 'AROON']
macros = ['housing_index', 'confidence_index', 'trade_index', 'longterm_rates', 'shortterm_rates']

In [11]:
dfaapl = apple.add_fundamentals(dfaapl, funs)

################################################################### 
 Ticker:  AAPL 
 Fundamentals Retrieved:  ['AAPL open' 'AAPL high' 'AAPL low' 'AAPL close' 'AAPL volume'
 'AAPL_totalrevenue' 'AAPL_totalcostofrevenue' 'AAPL_totalgrossprofit'
 'AAPL_totalpretaxincome' 'AAPL_weightedavebasicdilutedsharesos'
 'AAPL_cashdividendspershare' 'AAPL_quarter'] 
 ###################################################################
################################################################### 
 Ticker:  AAPL 
 Retrieved Data Start Date:  2009-07-22 
 Retrieved Data End Date:  2019-07-31 
 Data Retrieved:  ['AAPL_totalrevenue', 'AAPL_totalcostofrevenue', 'AAPL_totalgrossprofit', 'AAPL_totalpretaxincome', 'AAPL_weightedavebasicdilutedsharesos', 'AAPL_cashdividendspershare', 'AAPL_quarter'] 
 ###################################################################


In [12]:
dfaapl = apple.add_technicals(techs, dfaapl)

################################################################### 
 Ticker:  AAPL 
 Last Refreshed:  Simple Moving Average (SMA) 
 Data Retrieved:  2019-08-28 
 ###################################################################
################################################################### 
 Ticker:  AAPL 
 Last Refreshed:  Weighted Moving Average (WMA) 
 Data Retrieved:  2019-08-28 
 ###################################################################
################################################################### 
 Ticker:  AAPL 
 Last Refreshed:  Stochastic (STOCH) 
 Data Retrieved:  2019-08-28 
 ###################################################################
################################################################### 
 Ticker:  AAPL 
 Last Refreshed:  Rate of change : ((price/prevPrice)-1)*100 
 Data Retrieved:  2019-08-28 
 ###################################################################
################################################################### 

In [13]:
dfaapl = apple.add_macro(dfaapl, macros)

################################################################### 
 Index: Nominal Home Price Index Added 
 ###################################################################


/home/joe2/Documents/LambdaSchool/labs_ir/repos/Data-Science/data/fin_data.py:293: UserWarning: The latest value available for Housing Index is from January 2019.
  warnings.warn("The latest value available for Housing Index is from January 2019.")


################################################################### 
 Index: Yale Investor Behavior Project Added 
 ###################################################################
################################################################### 
 Trade Weighted U.S. Dollar Index: Broad Added 
 ###################################################################
################################################################### 
 US Treasury Bond Long-Term Rates Added 
 ###################################################################
################################################################### 
 US Treasury Bond Short-Term Rates Added 
 ###################################################################


/home/joe2/Documents/LambdaSchool/labs_ir/repos/Data-Science/data/fin_data.py:334: UserWarning: Contains Null Values
  warnings.warn("Contains Null Values")


In [14]:
dfaapl.head()

AAPL open  AAPL high  AAPL low  AAPL close  AAPL volume  \
date                                                                  
2019-01-31     166.11     169.00    164.56      166.44   40739600.0   
2019-01-30     163.25     166.15    160.23      165.25   61109800.0   
2019-01-29     156.25     158.13    154.11      154.68   41587200.0   
2019-01-28     155.79     156.33    153.66      156.30   26192100.0   
2019-01-25     155.48     158.13    154.32      157.76   33535500.0   

            AAPL_totalrevenue  AAPL_totalcostofrevenue  AAPL_totalgrossprofit  \
date                                                                            
2019-01-31       8.829300e+10             5.438100e+10           3.391200e+10   
2019-01-30       8.829300e+10             5.438100e+10           3.391200e+10   
2019-01-29       4.540800e+10             2.792000e+10           1.748800e+10   
2019-01-28       4.540800e+10             2.792000e+10           1.748800e+10   
2019-01-25       4.540800e+10             2.792000e+10           1.748800e+10   

            AAPL_totalpretaxincome  AAPL_weightedavebasicdilutedsharesos  ...  \
date                                                                      ...   
2019-01-31            2.703000e+10                          5.118600e+09  ...   
2019-01-30            2.703000e+10                          5.118600e+09  ...   
2019-01-29            1.130800e+10                          5.188700e+09  ...   
2019-01-28            1.130800e+10                          5.188700e+09  ...   
2019-01-25            1.130800e+10                          5.188700e+09  ...   

            4_Wk_DR 4_Wk_CE  8_Wk_DR  8_Wk_CE  13_Wk_DR  13_Wk_CE  26_Wk_DR  \
date                                                                          
2019-01-31     2.38    2.42     2.39     2.43      2.36      2.41      2.40   
2019-01-30     2.36    2.40     2.35     2.39      2.37      2.42      2.44   
2019-01-29     2.35    2.39     2.37     2.41      2.37      2.42      2.45   
2019-01-28     2.35    2.39     2.37     2.41      2.37      2.42      2.45   
2019-01-25     2.32    2.36     2.37     2.41      2.34      2.39      2.45   

            26_Wk_CE  52_Wk_DR  52_Wk_CE  
date                                      
2019-01-31      2.46      2.47      2.55  
2019-01-30      2.50      2.49      2.57  
2019-01-29      2.52      2.52      2.60  
2019-01-28      2.52      2.52      2.60  
2019-01-25      2.51      2.52      2.60  

[5 rows x 35 columns]

In [15]:
dfaapl.shape

(4300, 35)

In [16]:
dfaapl.isnull().sum()

AAPL open                                  0
AAPL high                                  0
AAPL low                                   0
AAPL close                                 0
AAPL volume                                0
AAPL_totalrevenue                       1901
AAPL_totalcostofrevenue                 1901
AAPL_totalgrossprofit                   1901
AAPL_totalpretaxincome                  1901
AAPL_weightedavebasicdilutedsharesos    1901
AAPL_cashdividendspershare              1901
AAPL_quarter                            1901
AAPL_SMA                                   0
AAPL_WMA                                   0
AAPL_SlowD                                 0
AAPL_SlowK                                 0
AAPL_ROC                                   0
AAPL_Aroon Down                            0
AAPL_Aroon Up                              0
housing_index                              0
conf_index                                 0
conf_index_SE                              0
trade_valu

In [17]:
dfaapl = dfaapl.drop(labels=['8_Wk_DR', '8_Wk_CE'], axis=1)

In [18]:
dfaapl_clean = dfaapl.dropna(axis=0)

In [19]:
dfaapl_clean.shape

(2398, 33)

In [20]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [21]:
pca = PCA(n_components=2)
mMscale = MinMaxScaler()

In [22]:
pca_tar = mMscale.fit_transform(dfaapl_clean[['AAPL open', 'AAPL close', 'AAPL high', 'AAPL low', 'AAPL volume']])

In [23]:
pca.fit(pca_tar)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [24]:
print(pca.components_)

[[ 0.49703139  0.49704388  0.49985896  0.49351104  0.11178125]
 [-0.05234709 -0.05729527 -0.04322941 -0.07082408  0.99352514]]


In [25]:
print(pca.explained_variance_)

[0.31576651 0.01302855]


In [26]:
two_comp = pca.transform(pca_tar)

In [29]:
pcatar_aapl = dfaapl_clean[['AAPL_totalrevenue', 'AAPL_totalcostofrevenue', 'AAPL_totalgrossprofit',
       'AAPL_totalpretaxincome', 'AAPL_weightedavebasicdilutedsharesos',
       'AAPL_cashdividendspershare', 'AAPL_SMA', 'AAPL_WMA',
       'AAPL_SlowK', 'AAPL_SlowD', 'AAPL_ROC', 'AAPL_Aroon Up',
       'AAPL_Aroon Down', 'housing_index', 'conf_index', 'conf_index_SE',
       'trade_value', '10 Yrs Rates', '20-Yr Maturity Rate', '4_Wk_DR',
       '4_Wk_CE', '13_Wk_DR', '13_Wk_CE', '26_Wk_DR', '26_Wk_CE', '52_Wk_DR',
       '52_Wk_CE']]

In [30]:
dfaapl_clean.columns

Index(['AAPL open', 'AAPL high', 'AAPL low', 'AAPL close', 'AAPL volume',
       'AAPL_totalrevenue', 'AAPL_totalcostofrevenue', 'AAPL_totalgrossprofit',
       'AAPL_totalpretaxincome', 'AAPL_weightedavebasicdilutedsharesos',
       'AAPL_cashdividendspershare', 'AAPL_quarter', 'AAPL_SMA', 'AAPL_WMA',
       'AAPL_SlowD', 'AAPL_SlowK', 'AAPL_ROC', 'AAPL_Aroon Down',
       'AAPL_Aroon Up', 'housing_index', 'conf_index', 'conf_index_SE',
       'trade_value', '10 Yrs Rates', '20-Yr Maturity Rate', '4_Wk_DR',
       '4_Wk_CE', '13_Wk_DR', '13_Wk_CE', '26_Wk_DR', '26_Wk_CE', '52_Wk_DR',
       '52_Wk_CE'],
      dtype='object')

In [31]:
np.gradient(dfaapl_clean['AAPL close'])

array([-1.19 , -5.88 , -4.475, ..., -1.14 , -1.623, -1.08 ])

In [33]:
dfaapl_clean = dfaapl_clean.drop('AAPL_quarter', axis=1)

In [34]:
dfaapl_clean.dtypes

AAPL open                               float64
AAPL high                               float64
AAPL low                                float64
AAPL close                              float64
AAPL volume                             float64
AAPL_totalrevenue                       float64
AAPL_totalcostofrevenue                 float64
AAPL_totalgrossprofit                   float64
AAPL_totalpretaxincome                  float64
AAPL_weightedavebasicdilutedsharesos    float64
AAPL_cashdividendspershare              float64
AAPL_SMA                                float64
AAPL_WMA                                float64
AAPL_SlowD                              float64
AAPL_SlowK                              float64
AAPL_ROC                                float64
AAPL_Aroon Down                         float64
AAPL_Aroon Up                           float64
housing_index                           float64
conf_index                              float64
conf_index_SE                           

In [157]:
# multivariate multi-step stacked lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense, Dropout, Embedding, LSTM

In [158]:
from keras import losses

In [136]:
dir(losses)

['K',
 'KLD',
 'MAE',
 'MAPE',
 'MSE',
 'MSLE',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'absolute_import',
 'binary_crossentropy',
 'categorical_crossentropy',
 'categorical_hinge',
 'cosine',
 'cosine_proximity',
 'deserialize',
 'deserialize_keras_object',
 'division',
 'get',
 'hinge',
 'kld',
 'kullback_leibler_divergence',
 'logcosh',
 'mae',
 'mape',
 'mean_absolute_error',
 'mean_absolute_percentage_error',
 'mean_squared_error',
 'mean_squared_logarithmic_error',
 'mse',
 'msle',
 'poisson',
 'print_function',
 'serialize',
 'serialize_keras_object',
 'six',
 'sparse_categorical_crossentropy',
 'squared_hinge']

In [36]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out-1
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [37]:
# define testing input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

In [38]:
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

In [53]:
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))


# choose a number of time steps
n_steps_in, n_steps_out = 3, 2


# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)

# get number of features
n_features = X.shape[2]

In [40]:
# define model
model = Sequential()
model.add(LSTM(100, activation='sigmoid', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')

Instructions for updating:
Colocations handled automatically by placer.


In [41]:
# fit model
model.fit(X, y, epochs=200, verbose=10)

Instructions for updating:
Use tf.cast instead.


In [42]:
# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[187.13326 210.0655 ]]


In [43]:
dfaapl_clean.to_numpy()

array([[166.11, 169.  , 164.56, ...,   2.46,   2.47,   2.55],
       [163.25, 166.15, 160.23, ...,   2.5 ,   2.49,   2.57],
       [156.25, 158.13, 154.11, ...,   2.52,   2.52,   2.6 ],
       ...,
       [156.95, 160.  , 156.5 , ...,   0.28,   0.43,   0.44],
       [156.63, 158.44, 155.56, ...,   0.28,   0.45,   0.46],
       [157.79, 158.73, 156.11, ...,   0.27,   0.43,   0.44]])

In [147]:
x_columns = dfaapl_clean.columns
X = {k:dfaapl_clean[k].to_numpy() for k in x_columns}
y = np.gradient(dfaapl_clean['AAPL close'].to_numpy())


In [148]:
for k in X.keys():
    l = len(X[k])
    X[k] = X[k].reshape(-1, 1)

In [149]:
y = y.reshape(-1, 1)

In [172]:
n_steps_in = 21
n_steps_out = 7



In [173]:
dataset = np.hstack([X[k] for k in X.keys()] + [y])

In [71]:
# dataset = []

In [174]:
X_split, y_split = split_sequences(dataset, n_steps_in=n_steps_in, n_steps_out=n_steps_out)

In [175]:
n_features = X_split.shape[2]

In [176]:
# define model
model = Sequential()
model.add(LSTM(100, activation='sigmoid', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(50, activation='sigmoid'))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mean_squared_error')

In [177]:
model.fit(X_split, y_split, epochs=500, validation_split=.2, shuffle=False, verbose=2)

Train on 1897 samples, validate on 475 samples
Epoch 1/500
 - 14s - loss: 98.3771 - val_loss: 8.9694
Epoch 2/500
 - 8s - loss: 98.3276 - val_loss: 8.9662
Epoch 3/500
 - 8s - loss: 98.3147 - val_loss: 8.9699
Epoch 4/500
 - 9s - loss: 98.3043 - val_loss: 8.9728
Epoch 5/500
 - 9s - loss: 98.2955 - val_loss: 8.9753
Epoch 6/500
 - 9s - loss: 98.2876 - val_loss: 8.9777
Epoch 7/500
 - 9s - loss: 98.2804 - val_loss: 8.9804
Epoch 8/500
 - 9s - loss: 98.2736 - val_loss: 8.9834
Epoch 9/500
 - 9s - loss: 98.2671 - val_loss: 8.9868
Epoch 10/500
 - 9s - loss: 98.2607 - val_loss: 8.9906
Epoch 11/500
 - 9s - loss: 98.2543 - val_loss: 8.9950
Epoch 12/500
 - 9s - loss: 98.2479 - val_loss: 8.9999
Epoch 13/500
 - 10s - loss: 98.2413 - val_loss: 9.0055
Epoch 14/500
 - 10s - loss: 98.2344 - val_loss: 9.0115
Epoch 15/500
 - 10s - loss: 98.2274 - val_loss: 9.0186
Epoch 16/500
 - 9s - loss: 98.2201 - val_loss: 9.0272
Epoch 17/500
 - 9s - loss: 98.2122 - val_loss: 9.0364
Epoch 18/500
 - 9s - loss: 98.2042 - val

In [181]:
prediction = model.predict(np.array([[dfaapl_clean.iloc[i:i+21].to_numpy()] for i in range(7)]).reshape(7,21,32))

In [179]:
np.gradient(dfaapl_clean['AAPL close'])[:7]

array([-1.19 , -5.88 , -4.475,  1.54 , -1.8  , -1.92 ,  0.3  ])

In [ ]:
# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

In [110]:
test_arr = array([[70, 75], [80, 85], [90, 95]])
test_arr_reshaped = x_input.reshape((1, 3, 2))
test_arr_reshaped

array([[[70, 75],
        [80, 85],
        [90, 95]]])

In [133]:
model.get_weights()

[array([[ 0.09145276,  0.08873188,  0.10333297, ..., -0.05087925,
         -0.10069062,  0.1033785 ],
        [-0.11160056, -0.06392359, -0.09621941, ..., -0.11491892,
          0.00463326,  0.03331599],
        [-0.06432565,  0.10922424,  0.02632555, ..., -0.06152768,
         -0.03659218, -0.00981131],
        ...,
        [-0.08431162,  0.02128317,  0.06179332, ...,  0.04532259,
         -0.10299102,  0.07582494],
        [-0.0735914 , -0.11449953,  0.10863789, ...,  0.04448358,
         -0.04677446, -0.10574875],
        [-0.02573206, -0.06052234,  0.10493629, ..., -0.04483202,
          0.00984795,  0.04517771]], dtype=float32),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], dtype=float32),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 

0

In [171]:
y_split

array([[ 7.775e+00, -8.450e-01, -7.950e-01, ..., -4.660e+00, -3.220e+00,
         5.000e+00],
       [-8.450e-01, -7.950e-01,  4.700e-01, ..., -3.220e+00,  5.000e+00,
         5.080e+00],
       [-7.950e-01,  4.700e-01, -4.660e+00, ...,  5.000e+00,  5.080e+00,
         4.620e+00],
       ...,
       [-1.080e+00, -1.820e+00, -1.680e+00, ...,  3.500e-02, -7.000e-03,
        -1.140e+00],
       [-1.820e+00, -1.680e+00, -1.395e+00, ..., -7.000e-03, -1.140e+00,
        -1.623e+00],
       [-1.680e+00, -1.395e+00,  3.500e-02, ..., -1.140e+00, -1.623e+00,
        -1.080e+00]])

In [180]:
test_arr = np.array([64,49,36,25,16,9,4,1,0,1,4,9,16,25,36,49,64])
np.gradient(test_arr)

array([-15., -14., -12., -10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,
         6.,   8.,  10.,  12.,  14.,  15.])

In [190]:
prediction[:, 0]

array([0.0567525 , 0.03734604, 0.03070688, 0.03070688, 0.03070688,
       0.03070688, 0.030707  ], dtype=float32)

In [193]:
dir(sp)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'LowLevelCallable',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '__SCIPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__numpy_version__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_lib',
 'absolute',
 'absolu

In [196]:
from fracdiff import FractionalDifferentiation